ktor {
    deployment {
        port = 8080
        host = "127.0.0.1"
        port = ${?PORT}
        host = ${?HOST}
    }
    application {
        modules =  [ dev.exposed.server.ServerKt.module ]
    }
}